# Generated by Django 5.0.6 on 2024-08-06 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntegrationPaymentsProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("policyNumber", models.CharField(max_length=50)),
                ("transactionDate", models.DateField(max_length=50)),
                ("transactionId", models.CharField(max_length=50)),
                ("paymentMethod", models.CharField(max_length=50)),
                ("sendNotification", models.BooleanField(verbose_name=False)),
                ("paymentDescription", models.CharField(max_length=500)),
                ("totalPaid", models.FloatField()),
                ("providerName", models.CharField(max_length=200)),
                ("status", models.CharField(default="ACTIVE", max_length=8)),
                ("paymentPeriods", models.CharField(max_length=5000)),
                ("payload", models.CharField(max_length=5000)),
            ],
            options={
                "db_table": "integration_payments_provider",
                "abstract": False,
            },
        ),
    ]
