# Generated by Django 5.0.6 on 2024-08-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrationapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationpaymentsprovider",
            name="providerName",
            field=models.CharField(default="Nombre Proveedor", max_length=200),
        ),
        migrations.AlterField(
            model_name="integrationpaymentsprovider",
            name="status",
            field=models.CharField(default="PENDING", max_length=8),
        ),
    ]
