# Generated by Django 5.0.6 on 2024-08-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "integrationapp",
            "0002_alter_integrationpaymentsprovider_providername_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationpaymentsprovider",
            name="pkintegrationevastatus",
            field=models.CharField(default="without information", max_length=200),
        ),
        migrations.AlterField(
            model_name="integrationpaymentsprovider",
            name="providerName",
            field=models.CharField(default="name provider", max_length=200),
        ),
    ]
