# Generated by Django 5.0.6 on 2024-08-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "integrationapp",
            "0003_integrationpaymentsprovider_pkintegrationevastatus_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="integrationpaymentsprovider",
            old_name="paymentDescription",
            new_name="payment_description",
        ),
        migrations.RenameField(
            model_name="integrationpaymentsprovider",
            old_name="paymentMethod",
            new_name="payment_method",
        ),
        migrations.RenameField(
            model_name="integrationpaymentsprovider",
            old_name="paymentPeriods",
            new_name="payment_periods",
        ),
        migrations.RenameField(
            model_name="integrationpaymentsprovider",
            old_name="pkintegrationevastatus",
            new_name="pk_integration_eva_status",
        ),
        migrations.RenameField(
            model_name="integrationpaymentsprovider",
            old_name="policyNumber",
            new_name="policy_number",
        ),
        migrations.RenameField(
            model_name="integrationpaymentsprovider",
            old_name="providerName",
            new_name="provider_name",
        ),
        migrations.RenameField(
            model_name="integrationpaymentsprovider",
            old_name="sendNotification",
            new_name="send_notification",
        ),
        migrations.RenameField(
            model_name="integrationpaymentsprovider",
            old_name="totalPaid",
            new_name="total_paid",
        ),
        migrations.RenameField(
            model_name="integrationpaymentsprovider",
            old_name="transactionDate",
            new_name="transaction_date",
        ),
        migrations.RenameField(
            model_name="integrationpaymentsprovider",
            old_name="transactionId",
            new_name="transaction_id",
        ),
    ]
